### ISSUE TITLE
Fix titles on main welcome infrastructure picture

### ISSUE THREAD

**Issue by usatko** [MediusInc/slotex-nlp-core#10]
Fix titles and picture on:
https://github.com/MediusInc/slotex-nlp-core/blob/master/docs/MediusNLP-microservice.jpg

1. construct new diagram flow with Mermaid (https://mermaidjs.github.io/)
2. see if Github supports such rendering on README.md
3. create PR

**Comment by MarkJuvan** [comment]
The picture is moved to slotex-nlp project (https://github.com/MediusInc/slotex-nlp/issues/12). 
This issue can be closed now.
