### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by usatko** [MediusInc/slotex-nlp-core#2]
Add license file

Apache or  MIT or gpl-3.0

**Comment by OpalJellyfish** [comment]
Hi, can I work on this issue?

**Comment by usatko** [comment]
Hello @OpalJellyfish thanks for your interest. We forgot to assign it to @peter-cebasek, who will try to solve this issue. He will made a shor presentation about proposed licences and that we will decide which to pick.

**Comment by cotnic** [comment]
@peter-cebasek I've added a TODO into the pom.xml where you can add the <license> details. 

Also please provide the LICENSE.md file where the GPL license will be defined. It's best to use the template that is already provided by GitHub.
